server:
  servlet:
    context-path: /api/v1

# spring
spring:
  application:
    name: nntask

# Other
wallets:
  supported-currencies: ${SUPPORTED_CURRENCIES:PLN,USD}
conversion:
  base-currency: ${BASE_CURRENCY:PLN}
integration:
  nbp:
    url: ${NBP_URL:https://api.nbp.pl/api/exchangerates/rates}